name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - multi-arch-support
    paths-ignore:
      - '**/*.md'

env:
  TZ: /usr/share/zoneinfo/Asia/Kathmandu
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

permissions:
  contents: read
  packages: write

jobs:
  generate-artifact:
    strategy:
      matrix:
        include:
          - name: amd64
            os: ubuntu-24.04
            platform: linux/amd64
          - name: arm64
            os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clone frappe_docker
        run: git clone --depth=1 https://github.com/frappe/frappe_docker

      - name: Build and push image
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: ./frappe_docker
          platforms: ${{ matrix.platform }}
          file: frappe_docker/images/custom/Containerfile
          push: true
          tags: docker.io/dockmyapp0/nepal-compliance:latest-${{ matrix.name }}
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            PYTHON_VERSION=3.11.9
            NODE_VERSION=18.20.2

  create-manifest:
    name: Create and Push Multi-Arch Manifest
    needs: generate-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create and Push Manifest
        run: |
          docker manifest create docker.io/dockmyapp0/nepal-compliance:latest \
            docker.io/dockmyapp0/nepal-compliance:latest-amd64 \
            docker.io/dockmyapp0/nepal-compliance:latest-arm64

          docker manifest push docker.io/dockmyapp0/nepal-compliance:latest

      - name: (Optional) Inspect Final Manifest
        run: |
          docker manifest inspect docker.io/dockmyapp0/nepal-compliance:latest
