# These rules guard against typical mistakes or bad practices while working on Frappe Framework apps.
# This workflow uses Frappe Semgrep rules specific to Frappe Framework, licensed under the MIT License.
# Copyright (c) 2021 Frappe Technologies Pvt. Ltd. <developers@frappe.io>. See LICENSE at https://github.com/frappe/semgrep-rules

name: Frappe Linter - Semgrep rules

on:
  workflow_call:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request: { }

# workflow can only read this repo’s code but cannot change
permissions:
  contents: read
  
jobs:
  linters:
    name: Frappe Linter
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache Semgrep rules
        uses: actions/cache@v4
        with:
          path: frappe-semgrep-rules
          key: semgrep-rules-${{ hashFiles('frappe-semgrep-rules/**') }}
          restore-keys: |
            semgrep-rules-

      - name: Download Semgrep rules
        if: steps.cache-semgrep-rules.outputs.cache-hit != 'true'
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Download semgrep
        run: pip install semgrep

      - name: Run Semgrep rules
        run: semgrep ci --config ./frappe-semgrep-rules/rules
